/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos, and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 - 2023 George MacKerron
Released under the MIT licence: see LICENCE file
*/

declare module 'zapatos/schema' {

  import type * as db from 'zapatos/db';

  // got a type error on schemaVersionCanary below? update by running `npx zapatos`
  export interface schemaVersionCanary extends db.SchemaVersionCanary { version: 104 }


  /* === schema: public === */

  /* --- enums --- */
  /* (none) */

  /* --- tables --- */

  /**
   * **schema_migrations**
   * - Table in database
   */
  export namespace schema_migrations {
    export type Table = 'schema_migrations';
    export interface Selectable {
      /**
      * **schema_migrations.version**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      version: string;
    }
    export interface JSONSelectable {
      /**
      * **schema_migrations.version**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      version: string;
    }
    export interface Whereable {
      /**
      * **schema_migrations.version**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      version?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **schema_migrations.version**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      version: string | db.Parameter<string> | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **schema_migrations.version**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      version?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
    }
    export type UniqueIndex = 'schema_migrations_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **users**
   * - Table in database
   */
  export namespace users {
    export type Table = 'users';
    export interface Selectable {
      /**
      * **users.avatar_url**
      * - `text` in database
      * - Nullable, no default
      */
      avatar_url: string | null;
      /**
      * **users.created_at**
      * - `timestamp` in database
      * - `NOT NULL`, default: `now()`
      */
      created_at: Date;
      /**
      * **users.email**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      email: string;
      /**
      * **users.first_name**
      * - `varchar` in database
      * - Nullable, no default
      */
      first_name: string | null;
      /**
      * **users.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('users_id_seq'::regclass)`
      */
      id: number;
      /**
      * **users.is_verified**
      * - `bool` in database
      * - `NOT NULL`, default: `false`
      */
      is_verified: boolean;
      /**
      * **users.last_name**
      * - `varchar` in database
      * - Nullable, no default
      */
      last_name: string | null;
      /**
      * **users.password_hash**
      * - `text` in database
      * - `NOT NULL`, default: `''::text`
      */
      password_hash: string;
      /**
      * **users.password_salt**
      * - `text` in database
      * - `NOT NULL`, default: `''::text`
      */
      password_salt: string;
      /**
      * **users.phone**
      * - `varchar` in database
      * - Nullable, no default
      */
      phone: string | null;
      /**
      * **users.seller_description**
      * - `text` in database
      * - Nullable, no default
      */
      seller_description: string | null;
      /**
      * **users.updated_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      updated_at: Date;
    }
    export interface JSONSelectable {
      /**
      * **users.avatar_url**
      * - `text` in database
      * - Nullable, no default
      */
      avatar_url: string | null;
      /**
      * **users.created_at**
      * - `timestamp` in database
      * - `NOT NULL`, default: `now()`
      */
      created_at: db.TimestampString;
      /**
      * **users.email**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      email: string;
      /**
      * **users.first_name**
      * - `varchar` in database
      * - Nullable, no default
      */
      first_name: string | null;
      /**
      * **users.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('users_id_seq'::regclass)`
      */
      id: number;
      /**
      * **users.is_verified**
      * - `bool` in database
      * - `NOT NULL`, default: `false`
      */
      is_verified: boolean;
      /**
      * **users.last_name**
      * - `varchar` in database
      * - Nullable, no default
      */
      last_name: string | null;
      /**
      * **users.password_hash**
      * - `text` in database
      * - `NOT NULL`, default: `''::text`
      */
      password_hash: string;
      /**
      * **users.password_salt**
      * - `text` in database
      * - `NOT NULL`, default: `''::text`
      */
      password_salt: string;
      /**
      * **users.phone**
      * - `varchar` in database
      * - Nullable, no default
      */
      phone: string | null;
      /**
      * **users.seller_description**
      * - `text` in database
      * - Nullable, no default
      */
      seller_description: string | null;
      /**
      * **users.updated_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      updated_at: db.TimestampTzString;
    }
    export interface Whereable {
      /**
      * **users.avatar_url**
      * - `text` in database
      * - Nullable, no default
      */
      avatar_url?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **users.created_at**
      * - `timestamp` in database
      * - `NOT NULL`, default: `now()`
      */
      created_at?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **users.email**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      email?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **users.first_name**
      * - `varchar` in database
      * - Nullable, no default
      */
      first_name?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **users.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('users_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **users.is_verified**
      * - `bool` in database
      * - `NOT NULL`, default: `false`
      */
      is_verified?: boolean | db.Parameter<boolean> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, boolean | db.Parameter<boolean> | db.SQLFragment | db.ParentColumn>;
      /**
      * **users.last_name**
      * - `varchar` in database
      * - Nullable, no default
      */
      last_name?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **users.password_hash**
      * - `text` in database
      * - `NOT NULL`, default: `''::text`
      */
      password_hash?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **users.password_salt**
      * - `text` in database
      * - `NOT NULL`, default: `''::text`
      */
      password_salt?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **users.phone**
      * - `varchar` in database
      * - Nullable, no default
      */
      phone?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **users.seller_description**
      * - `text` in database
      * - Nullable, no default
      */
      seller_description?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **users.updated_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      updated_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **users.avatar_url**
      * - `text` in database
      * - Nullable, no default
      */
      avatar_url?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **users.created_at**
      * - `timestamp` in database
      * - `NOT NULL`, default: `now()`
      */
      created_at?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment;
      /**
      * **users.email**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      email: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **users.first_name**
      * - `varchar` in database
      * - Nullable, no default
      */
      first_name?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **users.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('users_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      /**
      * **users.is_verified**
      * - `bool` in database
      * - `NOT NULL`, default: `false`
      */
      is_verified?: boolean | db.Parameter<boolean> | db.DefaultType | db.SQLFragment;
      /**
      * **users.last_name**
      * - `varchar` in database
      * - Nullable, no default
      */
      last_name?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **users.password_hash**
      * - `text` in database
      * - `NOT NULL`, default: `''::text`
      */
      password_hash?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment;
      /**
      * **users.password_salt**
      * - `text` in database
      * - `NOT NULL`, default: `''::text`
      */
      password_salt?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment;
      /**
      * **users.phone**
      * - `varchar` in database
      * - Nullable, no default
      */
      phone?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **users.seller_description**
      * - `text` in database
      * - Nullable, no default
      */
      seller_description?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **users.updated_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      updated_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **users.avatar_url**
      * - `text` in database
      * - Nullable, no default
      */
      avatar_url?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **users.created_at**
      * - `timestamp` in database
      * - `NOT NULL`, default: `now()`
      */
      created_at?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment>;
      /**
      * **users.email**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      email?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **users.first_name**
      * - `varchar` in database
      * - Nullable, no default
      */
      first_name?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **users.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('users_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
      /**
      * **users.is_verified**
      * - `bool` in database
      * - `NOT NULL`, default: `false`
      */
      is_verified?: boolean | db.Parameter<boolean> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, boolean | db.Parameter<boolean> | db.DefaultType | db.SQLFragment>;
      /**
      * **users.last_name**
      * - `varchar` in database
      * - Nullable, no default
      */
      last_name?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **users.password_hash**
      * - `text` in database
      * - `NOT NULL`, default: `''::text`
      */
      password_hash?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.DefaultType | db.SQLFragment>;
      /**
      * **users.password_salt**
      * - `text` in database
      * - `NOT NULL`, default: `''::text`
      */
      password_salt?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.DefaultType | db.SQLFragment>;
      /**
      * **users.phone**
      * - `varchar` in database
      * - Nullable, no default
      */
      phone?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **users.seller_description**
      * - `text` in database
      * - Nullable, no default
      */
      seller_description?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **users.updated_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      updated_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'users_email_key' | 'users_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /* --- aggregate types --- */

  export namespace public {  
    export type Table = schema_migrations.Table | users.Table;
    export type Selectable = schema_migrations.Selectable | users.Selectable;
    export type JSONSelectable = schema_migrations.JSONSelectable | users.JSONSelectable;
    export type Whereable = schema_migrations.Whereable | users.Whereable;
    export type Insertable = schema_migrations.Insertable | users.Insertable;
    export type Updatable = schema_migrations.Updatable | users.Updatable;
    export type UniqueIndex = schema_migrations.UniqueIndex | users.UniqueIndex;
    export type Column = schema_migrations.Column | users.Column;
  
    export type AllBaseTables = [schema_migrations.Table, users.Table];
    export type AllForeignTables = [];
    export type AllViews = [];
    export type AllMaterializedViews = [];
    export type AllTablesAndViews = [schema_migrations.Table, users.Table];
  }



  /* === global aggregate types === */

  export type Schema = 'public';
  export type Table = public.Table;
  export type Selectable = public.Selectable;
  export type JSONSelectable = public.JSONSelectable;
  export type Whereable = public.Whereable;
  export type Insertable = public.Insertable;
  export type Updatable = public.Updatable;
  export type UniqueIndex = public.UniqueIndex;
  export type Column = public.Column;

  export type AllSchemas = ['public'];
  export type AllBaseTables = [...public.AllBaseTables];
  export type AllForeignTables = [...public.AllForeignTables];
  export type AllViews = [...public.AllViews];
  export type AllMaterializedViews = [...public.AllMaterializedViews];
  export type AllTablesAndViews = [...public.AllTablesAndViews];


  /* === lookups === */

  export type SelectableForTable<T extends Table> = {
    "schema_migrations": schema_migrations.Selectable;
    "users": users.Selectable;
  }[T];

  export type JSONSelectableForTable<T extends Table> = {
    "schema_migrations": schema_migrations.JSONSelectable;
    "users": users.JSONSelectable;
  }[T];

  export type WhereableForTable<T extends Table> = {
    "schema_migrations": schema_migrations.Whereable;
    "users": users.Whereable;
  }[T];

  export type InsertableForTable<T extends Table> = {
    "schema_migrations": schema_migrations.Insertable;
    "users": users.Insertable;
  }[T];

  export type UpdatableForTable<T extends Table> = {
    "schema_migrations": schema_migrations.Updatable;
    "users": users.Updatable;
  }[T];

  export type UniqueIndexForTable<T extends Table> = {
    "schema_migrations": schema_migrations.UniqueIndex;
    "users": users.UniqueIndex;
  }[T];

  export type ColumnForTable<T extends Table> = {
    "schema_migrations": schema_migrations.Column;
    "users": users.Column;
  }[T];

  export type SQLForTable<T extends Table> = {
    "schema_migrations": schema_migrations.SQL;
    "users": users.SQL;
  }[T];

}
